org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
fabric.loom.multiProjectOptimisation=true

project.group=net.aosankaku.liteminerdelta
project.plugins=3.0-SNAPSHOT

mod.name=Liteminer Delta
mod.authors=AoSankaku
mod.id=liteminer_delta
mod.license=MIT
mod.credits=Based on the original Liteminer by iamkaf
mod.description=An independently maintained fork of Liteminer.

publish.dry-run=false
publish.curseforge.id=
publish.modrinth.id=liteminer-delta
publish.release-type=release
publish.game-versions=auto
publish.changelog.final-file=release-notes.md
environments.client=optional
environments.server=optional

mixin.compat.common=JAVA_25
mixin.compat.fabric=JAVA_25
mixin.compat.forge=JAVA_25
mixin.compat.neoforge=JAVA_25
